# esg_ml/infraestrutura/inicializacao_banco.py
import argparse
import os

from sqlalchemy.orm import Session

from esg_ml.infraestrutura.banco_dados import (
    Base, SessaoLocal, criar_tabelas, engine, obter_url_banco_mascarada,
)
from esg_ml.infraestrutura.modelos_banco import UsuarioBanco
from esg_ml.infraestrutura.seguranca import gerar_hash_senha
from esg_ml.infraestrutura.registro_log import obter_registrador

registrador = obter_registrador(__name__)

EMAIL_ADMIN_PADRAO = 'admin@esgnexus.example'
SENHA_ADMIN_PADRAO = 'admin123'


# ── helpers ───────────────────────────────────────────────────────────────────

def _criar_usuario_se_ausente(
    sessao: Session,
    email: str,
    senha: str,
    nome: str,
    perfil: str,
) -> tuple[UsuarioBanco, bool]:
    """Cria o usuário se não existir. Retorna (usuario, criado)."""
    existente = sessao.query(UsuarioBanco).filter(
        UsuarioBanco.email == email
    ).first()
    if existente is not None:
        return existente, False
    usuario = UsuarioBanco(
        nome=nome,
        email=email,
        senha_hash=gerar_hash_senha(senha),
        perfil=perfil,
        ativo=True,
    )
    sessao.add(usuario)
    sessao.commit()
    sessao.refresh(usuario)
    return usuario, True


# ── API pública ───────────────────────────────────────────────────────────────

def _migrar_identity() -> None:
    """Converte PKs SERIAL para GENERATED BY DEFAULT AS IDENTITY (PostgreSQL 10+).

    Idempotente: ignora tabelas inexistentes e colunas já configuradas como IDENTITY.
    Não executa em dialetos não-PostgreSQL (ex.: SQLite usado em testes).
    """
    if not engine.dialect.name.startswith('postgresql'):
        return

    from sqlalchemy import inspect, text

    tabelas = ['usuarios', 'fornecedores', 'avaliacoes_esg', 'planos_acao', 'experimentos_ml']

    with engine.begin() as conn:
        insp = inspect(conn)
        for tabela in tabelas:
            if not insp.has_table(tabela):
                continue

            row = conn.execute(text(
                "SELECT column_default, identity_generation "
                "FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = :t AND column_name = 'id'"
            ), {'t': tabela}).fetchone()

            if row is None or row.identity_generation is not None:
                continue  # tabela ausente ou id já é IDENTITY

            max_id = conn.execute(
                text(f'SELECT COALESCE(MAX(id), 0) + 1 FROM {tabela}')
            ).scalar()

            if row.column_default and 'nextval' in str(row.column_default):
                # SERIAL: remove o default da sequência, adiciona IDENTITY e descarta sequência órfã
                conn.execute(text(f'ALTER TABLE {tabela} ALTER COLUMN id DROP DEFAULT'))
                conn.execute(text(
                    f'ALTER TABLE {tabela} ALTER COLUMN id '
                    f'ADD GENERATED BY DEFAULT AS IDENTITY (START WITH {max_id})'
                ))
                conn.execute(text(f'DROP SEQUENCE IF EXISTS {tabela}_id_seq'))
            else:
                conn.execute(text(
                    f'ALTER TABLE {tabela} ALTER COLUMN id '
                    f'ADD GENERATED BY DEFAULT AS IDENTITY (START WITH {max_id})'
                ))

            registrador.info('identity_migrado', tabela=tabela, proximo_id=max_id)


def _criar_view_fornecedores_classificacoes() -> None:
    """Cria ou substitui a view vw_fornecedores_classificacoes.

    Lista cada fornecedor com sua classificação ESG mais recente e os itens
    do plano de ação vinculados. Retorna uma linha por item de plano de ação
    (ou uma linha sem plano quando não há avaliação ainda).
    Requer PostgreSQL (usa LATERAL JOIN).
    """
    if not engine.dialect.name.startswith('postgresql'):
        return

    from sqlalchemy import text

    with engine.begin() as conn:
        conn.execute(text("""
            CREATE OR REPLACE VIEW vw_fornecedores_classificacoes AS
            SELECT
                f.id                        AS fornecedor_id,
                f.name                      AS razao_social,
                f.industry                  AS setor,
                f.cnpj,
                f.environment_score,
                f.social_score,
                f.governance_score,
                f.criado_em                 AS fornecedor_criado_em,
                a.id                        AS avaliacao_id,
                a.total_score,
                a.score_ponderado,
                ROUND((a.score_ponderado / 10.0)::NUMERIC, 1)  AS pontuacao_esg,
                a.grade,
                a.level,
                a.risco,
                a.impacto,
                a.quadrante,
                a.maturidade_rf,
                a.confianca_rf_high,
                a.maturidade_knn,
                a.confianca_knn_high,
                a."w_E"                     AS w_e,
                a."w_S"                     AS w_s,
                a."w_G"                     AS w_g,
                a.fonte_pesos,
                a.criado_em                 AS avaliacao_criado_em,
                p.id                        AS plano_id,
                p.pilar,
                p.score                     AS pilar_score,
                p.importancia,
                p.acao
            FROM fornecedores f
            LEFT JOIN LATERAL (
                SELECT *
                FROM   avaliacoes_esg
                WHERE  fornecedor_id = f.id
                ORDER  BY criado_em DESC
                LIMIT  1
            ) a ON true
            LEFT JOIN planos_acao p ON p.avaliacao_id = a.id
            ORDER BY f.name, p.importancia DESC NULLS LAST
        """))
        registrador.info('view_criada_ou_atualizada', view='vw_fornecedores_classificacoes')


def _migrar_experimentos_ml() -> None:
    """Adiciona colunas de precisão/recall à tabela experimentos_ml sem perder dados."""
    from sqlalchemy import inspect, text
    insp = inspect(engine)
    if not insp.has_table('experimentos_ml'):
        return
    existentes = {c['name'] for c in insp.get_columns('experimentos_ml')}
    novas = {
        'rf_precision':  'DOUBLE PRECISION',
        'rf_recall':     'DOUBLE PRECISION',
        'knn_precision': 'DOUBLE PRECISION',
        'knn_recall':    'DOUBLE PRECISION',
    }
    with engine.begin() as conn:
        for col, tipo in novas.items():
            if col not in existentes:
                conn.execute(text(f'ALTER TABLE experimentos_ml ADD COLUMN {col} {tipo}'))
                registrador.info('coluna_adicionada', tabela='experimentos_ml', coluna=col)


def semear_banco() -> None:
    """Cria tabelas e seeds de usuários padrão.

    Chamado no startup da API (lifespan). Idempotente — seguro para rodar
    a cada reinicialização do contêiner.
    """
    registrador.info('semear_banco_inicio', banco=obter_url_banco_mascarada())

    # 1) Migrações estruturais → criação de tabelas → objetos dependentes (views)
    _migrar_experimentos_ml()
    _migrar_identity()
    criar_tabelas()
    _criar_view_fornecedores_classificacoes()

    with SessaoLocal() as sessao:
        # 2) Administrador padrão (variáveis USUARIO_ADMIN_*)
        admin_email = os.getenv('USUARIO_ADMIN_EMAIL', EMAIL_ADMIN_PADRAO)
        admin_senha = os.getenv('USUARIO_ADMIN_SENHA', SENHA_ADMIN_PADRAO)
        admin_nome  = os.getenv('USUARIO_ADMIN_NOME',  'Administrador ESG Nexus')
        usuario, criado = _criar_usuario_se_ausente(
            sessao, admin_email, admin_senha, admin_nome, 'administrador',
        )
        if criado:
            registrador.info('admin_criado', email=usuario.email)
            if admin_email == EMAIL_ADMIN_PADRAO:
                registrador.warning(
                    'senha_padrao_em_uso',
                    aviso='Altere USUARIO_ADMIN_SENHA antes de usar em produção',
                )
        else:
            registrador.info('admin_ja_existe', email=usuario.email)

        # 3) Conta de serviço do Airflow (variáveis ESG_ADMIN_*)
        airflow_email = os.getenv('ESG_ADMIN_EMAIL')
        airflow_senha = os.getenv('ESG_ADMIN_SENHA')
        if airflow_email and airflow_senha:
            svc, criado_svc = _criar_usuario_se_ausente(
                sessao,
                email=airflow_email,
                senha=airflow_senha,
                nome='Airflow Service Account',
                perfil='administrador',
            )
            if criado_svc:
                registrador.info('conta_servico_criada', email=svc.email)
            else:
                registrador.info('conta_servico_ja_existe', email=svc.email)

    registrador.info('semear_banco_concluido')


# ── CLI (manutenção / migrations) ─────────────────────────────────────────────

def criar_usuario_admin(sessao: Session) -> UsuarioBanco:
    """Atalho legado usado pelo CLI."""
    email = os.getenv('USUARIO_ADMIN_EMAIL', EMAIL_ADMIN_PADRAO)
    senha = os.getenv('USUARIO_ADMIN_SENHA', SENHA_ADMIN_PADRAO)
    nome  = os.getenv('USUARIO_ADMIN_NOME',  'Administrador ESG Nexus')
    usuario, _ = _criar_usuario_se_ausente(sessao, email, senha, nome, 'administrador')
    return usuario


def executar() -> None:
    parser = argparse.ArgumentParser(description='Inicializa o banco ESG Nexus Enterprise.')
    parser.add_argument('--recriar', action='store_true',
                        help='Drop + create all (APAGA TODOS OS DADOS)')
    parser.add_argument('--sem-admin', action='store_true',
                        help='Não cria usuário administrador padrão')
    args = parser.parse_args()

    print(f'Banco: {obter_url_banco_mascarada()}')
    from sqlalchemy import text
    with engine.connect() as c:
        c.execute(text('select 1'))
    print('Conexão OK.')

    if args.recriar:
        from esg_ml.infraestrutura import modelos_banco  # noqa: F401
        print('Recriando tabelas (drop all)...')
        Base.metadata.drop_all(bind=engine)

    _migrar_experimentos_ml()
    _migrar_identity()
    criar_tabelas()
    _criar_view_fornecedores_classificacoes()
    print('Tabelas criadas/verificadas. Views criadas/atualizadas.')

    if not args.sem_admin:
        with SessaoLocal() as sessao:
            u, criado = _criar_usuario_se_ausente(
                sessao,
                os.getenv('USUARIO_ADMIN_EMAIL', EMAIL_ADMIN_PADRAO),
                os.getenv('USUARIO_ADMIN_SENHA', SENHA_ADMIN_PADRAO),
                os.getenv('USUARIO_ADMIN_NOME',  'Administrador ESG Nexus'),
                'administrador',
            )
            status = 'criado' if criado else 'já existia'
            print(f'Usuário admin ({status}): {u.email}')
            if criado and u.email == EMAIL_ADMIN_PADRAO:
                print(f'  Senha inicial: {SENHA_ADMIN_PADRAO}  ← altere antes de usar em produção')

    print('Banco inicializado com sucesso.')


if __name__ == '__main__':
    executar()
