server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/esg_nexus
    username: esg_user
    password: esg_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yRVNHTmV4dXNBcHAxMjM0NTY3ODkw
    expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
